Support Android Nougat #5
MeetMe/font-compat pull request #6
Opened 2016-09-01 13:52 UTC by iainalba

As described in this issue:

[https://github.com/MeetMe/font-compat/issues/5](url)

the FontManager was only including Android N Preview versions. As a result a Font Manager Implementation class was not being assigned to `IMPL` when running with Android N. Therefore, the logic was altered to allow Android versions `>=` Marshmallow to use `FontManagerImpl24()`.

2016-09-01 19:11 UTC, troyjperales commented
Thanks, @iainalba . I would have done a PR, but I haven't had much response with my previous ones ;)

2016-11-07 08:01 UTC, Aditya-Sh commented
I have used the above fix and it started working on Android N but now it crashes on Android M. The error is same as before but now it's on Android M. 
`java.lang.NoSuchMethodError: No virtual method addFontWeightStyle(Ljava/nio/ByteBuffer;ILjava/util/List;IZ)Z in class Landroid/graphics/FontFamily; or its super classes (declaration of 'android.graphics.FontFamily' appears in /system/framework/framework.jar)`

2016-11-07 09:28 UTC, iainalba commented
Yeh I realised I made a stupid mistake, but never pushed my changes. I'll push them now.

2016-11-07 09:33 UTC, Aditya-Sh commented
Thank you for the prompt reply. Are you updating the master branch?

2016-11-09 18:05 UTC, Aditya-Sh commented
@iainalba The latest committed changes work. Thank you.

2017-01-20 20:00 UTC, rogercotrina commented
Hi @jhansche, are there any future plans to merge this PR and doing a new release of the library?

2017-01-20 20:14 UTC, jhansche requested changes
Ideally the compileSdkVersion should be updated, so that you can use `Build.VERSION_CODES.N` instead of a hard-coded `24`

2017-01-20 20:14 UTC, jhansche commented on library/src/main/java/com/meetme/support/fonts/FontManager.java
> +        if (Build.VERSION.SDK_INT >= 24) {
This should use Build.VERSION_CODES.N, by updating compileSdkVersion to 24+

2017-01-20 20:14 UTC, jhansche commented on library/src/main/java/com/meetme/support/fonts/FontManager.java
> +        if (Build.VERSION.SDK_INT >= 24) {
Also, IIRC, there were differences even within the Nougat preview releases.  It's been a while, but I thought I had to make changes as newer releases were coming out.

Granted, those were previews, and ideally should not be shipped on production devices, so arguably not worth digging too far into.

2017-01-20 20:16 UTC, jhansche commented
Sorry all for not getting back to these... I don't recall seeing any notifications for the existing issues and PRs, until this morning. 😬 

As for a new release @rogercotrina, I do think it makes sense to do a new release when these are merged. I'll just have to remember how to do the release 😕

2017-01-20 20:23 UTC, troyjperales commented on library/src/main/java/com/meetme/support/fonts/FontManager.java
> +        if (Build.VERSION.SDK_INT >= 24) {
I agree with using version codes provided by framework and not worrying about preview releases. I already pulled in the source to support a project I was on last year. I'm supposed to jump back on that project some time next week and can update this. But hopefully @iainalba can get around to it before that.

Thanks for getting back to us @jhansche !

2017-02-15 19:05 UTC, leodeleon22 commented
Someone accept this merge for the love of God!

2017-02-15 19:05 UTC, leodeleon22 commented on library/src/main/java/com/meetme/support/fonts/FontManager.java
> +        if (Build.VERSION.SDK_INT >= 24) {
Looking forward a solution here :)

2017-06-15 16:28 UTC, jaggs6 commented
@jhansche can this be merged if everything is fine? Thanks

2017-06-15 18:38 UTC, merged

2017-07-30 22:48 UTC, fangzhzh commented
Thanks. Need a new release for it.